### ISSUE TITLE
BUG Report - wrong search for sDelete in Windows system folder v1.3.0

### ISSUE THREAD

**Issue by RAJUPROP** [Tulpep/SDelete-Gui#10]
In Windows 10 , sDelete-GUI 1.3.0 searches in sysWow64 folder for sDelete.exe instead of (to search for) sDelete64.exe and NOT searches in system32 folder for sDelete.exe.... This is a big BUG.... Only sDelete64.exe can be copied to sysWow folder. If we copy sDelete.exe to sysWow folder (instead of sDelete64.exe) , for the next time , Windows will automatically remove sDelete.exe from the sysWow folder. Also, the program doesn't search in system32 folder for sDelete.exe....

**Comment by ricardopolo** [comment]
Thanks for the report, I will take a look next week!

**Comment by abyssox** [comment]
I think there's some misunderstanding of system32 and SysWOW64 folder.
SysWOW64 is for 32-bit applications and system32 is for 64-bit applications:
https://www.howtogeek.com/326509/whats-the-difference-between-the-system32-and-syswow64-folders-in-windows

**Comment by ricardopolo** [comment]
Fixed, working and published in 1.3.4. Thanks a lot @abyssox !
