### ISSUE TITLE
How to remove context menu?

### ISSUE THREAD

**Issue by pstein** [Tulpep/SDelete-Gui#17]
SDelete-GUI automatically setup Windows Explorer context menu.

In case I don't want to use it any longer:

How do I remove this context menu later?

**Comment by adamyaxley** [comment]
Run the GUI again and click "Disable". This should remove the "Secure Delete" option from the context menu,

**Comment by ricardopolo** [comment]
Yes. In this way you uninstalled it. 

If you have any other question let us know!

**Comment by pstein** [comment]
So ok, I started SDelete GUI from my USB flash drive and SDelete GUI tells me

"SDelete.exe not found in C:\Windows\SysWOW64 and cannot be downloaded from Internet"

very bad. 

SDelete-GUI.exe is stored and run from the same directory as sdelete.exe and sdelete64.exe

Why does GUI not automatically look in its current folder for the SDelete64.exe?

How can I manually pass another absolute/relative path to  to SDelete64.exe?
e.g.

SDelete-GUI.exe -lookpath="H:\tools\sdelete\"

**Comment by ricardopolo** [comment]
Sdelete GUI downloads Sdelete from Microsoft or use the current one in system32. 

Is it possible to you to copy Sdelete to the Syswow64 folder?

if any one can add a PR for adding a relative path we will release a new version with your suggested improvement.

**Comment by pstein** [comment]
>Is it possible to you to copy Sdelete to the Syswow64 folder?

I don't want to copy any files.
Good software should work out of the box when necessary sub programs are put in their installation folder.

**Comment by ricardopolo** [comment]
Remember this is a free, open-source tool. If you can help we accept your improvements.
