### ISSUE TITLE
The latest 1.0.66 release is broken

### ISSUE THREAD

**Issue by zenima** [Tulpep/SDelete-Gui#3]
Hey!
It seems the latest release [1.0.66](https://github.com/Tulpep/SDelete-Gui/tree/SDelete-Gui-v1.0.66), 401f0d40cc659f9a7520121f80c7ee917feb665b is broken - when I try to run it, it simply exists.

Since it's only 23 KB, while previous versions were around 350 KB, I checked with dotPeek.  **Turns out the dependencies were are not included the executable**. I assume it must be a faulty configuration in AppVeyor since the commits between the two versions look okay.

Checking the logs of the two build ([1.0.66 log](https://ci.appveyor.com/project/tulpep/sdelete-gui/build/1.0.66) and [1.0.62 log](https://ci.appveyor.com/project/tulpep/sdelete-gui/build/1.0.62)), you can see, that the WinFodyTarget build step was skipped last time.

**Comment by zenima** [comment]
_On a side note.._

I run into another issue, but it happens because of the latest version of sdelete (2.0, released in July 2016).., It throws a few errors then starts to clean the free space on the disk when executed, so becomes extremely slow. There are [several posts](http://forum.sysinternals.com/search_results_posts.asp?SearchID=20161210100416&KW=sdelete+2%2E0) about this on their message board, hopefully it will be fixed soon.
Unfortunately no previous versions are available and their licensing does not allow to include it in the repository here.

**Comment by ricardopolo** [comment]
Thanks for the report @zenima. I'll check on that today

**Comment by ricardopolo** [comment]
@zenima you are totally right. It was broken. 

The build was not with problems but the version published in Github Releases was.
I made some commits, and release a new version. This includes a new digital signature. 

Please confirm me if everything works or you have any issue to reopen this.
