### ISSUE TITLE
Proxy issue

### ISSUE THREAD

**Issue by JakeLD** [Tulpep/SDelete-Gui#4]
Hi,

I can't make this tools work behind a proxy. Also, most enteprise servers won't have direct Internet access, so it would be ncie if the tool could work when sdelete is detected in Syswow64. Thank you! Regards,

**Comment by ricardopolo** [comment]
@JakeLD thanks

I just published a new version with your requirement. The tool will try to download SDelete from Sysinternals, if the download fails it will check if the file exists. If the file exists it will continue without errors.

Please confirm it works as expected. 

Regards

**Comment by JakeLD** [comment]
Works!  Thanks

On Mon, Feb 20, 2017, 2:23 PM Ricardo Polo, <notifications@github.com>
wrote:

@JakeLD <https://github.com/JakeLD> thanks

I just published a new version with your requirement. The tool will try to
download SDelete from Sysinternals, if the download fails it will check if
the file exists. If the file exists it will continue without errors.

Please confirm it works as expected.

Regards

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Tulpep/SDelete-Gui/issues/4#issuecomment-281162491>,
or mute
the thread
